config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :posts do
		resources :likes
		resources :comments do
		resources :image
	end
	end
	root 'posts#index'
	end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_one_attached :image
	has_many :likes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts
    has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
   before_action :find_post
   before_action :find_like, only: [:destroy]

  def create
  	if already_liked?
  		flash[:notice] = "You can't like more than once"
  	else
  		@post.likes.create(user_id: current_user.id)
  	end
  	redirect_to post_path(@post)
  end


  def destroy
  	if !(already_liked?)
  		flash[:notice] = "Cannot unlike"
  	else
  		@like.destroy
  	end
  	redirect_to post_path(@post)
  end
  

  def find_like
  	@like = @post.likes.find(params[:id])
  end

  
  private

  def find_post
  	@post = Post.find(params[:post_id])
  end

  def already_liked?
  	Like.where(user_id: current_user.id, post_id:
  	params[:post_id]).exists?
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]




	def index
		@posts = Post.all.order("created_at DESC")	
	end

	def show
		
	end


	def new
		@post = current_user.posts.new
	end


	def create
		@post = current_user.posts.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end


	def edit

	end


	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end


	end

	def destroy
		logger.debug "total comments for this post are: #{@post.comments.count}"
		@post.comments.each do |d|
			d.destroy
		end
		@post.destroy
		redirect_to root_path
	end




	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email
	.buttons
		= link_to "Edit", edit_post_comment_path(comment.post, comment)
		= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.new]) do |f|
 = f.input :comment
 = f.submit

app/views/comments/edit.html.haml
%h1 Edit comment
= simple_form_for([@post, @comment]) do |f| 
 = f.input :comment
 = f.submit

app/views/layouts/application.html.haml
!!!
%html 
%head
  %title Demo Projects
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  %link{ rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Lato", type: "text/css" }
  %link{ rel: "stylesheet", href: "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" }
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %header.main_header.clearfix
    .wrapper
      #logo 
        %p= link_to "Demo Projects", root_path
      #buttons
        - if user_signed_in?
          = link_to "New Post", new_post_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Sign Up", new_user_registration_path
          = link_to "Sign In", new_user_session_path   

  .wrapper
    %p.notice= notice
    %p.alert= alert
  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.input :image
  = f.submit

app/views/posts/edit.html.haml
%h1 edit post

= render 'form'

= link_to"cancel",post_path

app/views/posts/index.html.haml
#posts
 - @posts.each do |post|
  .post
   %h2.title= link_to post.title, post
   %p.date
    Published at
    = time_ago_in_words(post.created_at)
   %p
    = post.likes.count
    = (post.likes.count) == 1 ? 'Like' : 'Likes'


    <a = image_tag(link_to(post.image))>

app/views/posts/new.html.haml
%h1 Hii this is the new post page.

= render 'form'

app/views/posts/show.html.haml
#post_content 
 %h1= @post.title
 %h5
 = @post.content
 %p
 =image_tag((@post.image), :size => "360x360")
 %p
 = @post.likes.count
 = (@post.likes.count) == 1 ? 'Like' : 'Likes'
 - pre_like = @post.likes.find { |like| like.user_id == current_user.id}
 - if pre_like
  = button_to 'Unlike', post_like_path(@post, pre_like), method: :delete
 - else
  = button_to 'Like', post_likes_path(@post), method: :post

 #comments
  %h2
   = @post.comments.count
   Comments 
  = render @post.comments
  %h3 Comments for post
  = render "comments/form"
 %br/
 %hr/
 %br/

 = link_to "Edit", edit_post_path(@post), class: "button"
 = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this ?" }, class: "button"
 = link_to "Home", root_path, class: "button"


 